version: "3.9"
services:
  db:
    image: bitnami/postgresql:14.1.0
    ports:
      - '5433:5432'
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: 123123123
      POSTGRESQL_DATABASE: minibank
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  migrate:
    image: migrate/migrate:v4.15.1
    volumes:
      - ./db/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgresql://postgres:123123123@db:5432/minibank?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy
  backend:
    build: .
    environment:
      PORT: 3000
      HASH_SALT: HASH_SALT
      SIGNING_KEY: SIGNING_KEY
      TOKEN_TTL: 86400
      DATABASE_URL: postgresql://postgres:123123123@db:5432/minibank?sslmode=disable
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:1.21.4-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '5050:80'
    depends_on:
      - backend
