// Code generated by sqlc. DO NOT EDIT.

package postgresql

import (
	"database/sql"
	"time"
)

type Account struct {
	ID         int32         `json:"id"`
	UserID     sql.NullInt64 `json:"user_id"`
	BankID     sql.NullInt64 `json:"bank_id"`
	Name       string        `json:"name"`
	Balance    sql.NullInt64 `json:"balance"`
	InsertedAt time.Time     `json:"inserted_at"`
	UpdatedAt  time.Time     `json:"updated_at"`
}

type Bank struct {
	ID         int32     `json:"id"`
	Name       string    `json:"name"`
	InsertedAt time.Time `json:"inserted_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Transaction struct {
	ID         int32         `json:"id"`
	AccountID  sql.NullInt64 `json:"account_id"`
	Amount     sql.NullInt64 `json:"amount"`
	Type       string        `json:"type"`
	InsertedAt time.Time     `json:"inserted_at"`
	UpdatedAt  time.Time     `json:"updated_at"`
}

type User struct {
	ID         int32     `json:"id"`
	Email      string    `json:"email"`
	Password   string    `json:"password"`
	Role       string    `json:"role"`
	InsertedAt time.Time `json:"inserted_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}
