name: ci-test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  DATABASE_URL: postgresql://postgres:123123123@db:5432/minibank?sslmode=disable

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123123123
          POSTGRES_DB: minibank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - uses: actions/checkout@v2

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/migrate
          which migrate

      - name: Run migrations
        run: migrate -path db/migrations -database $DATABASE_URL up

      - name: Test
        run: make test
